/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stdin.stdout.i;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasGetInputString() {
        App classUnderTest = new App();
        String inputString = "Hello, World.";
        classUnderTest.setInputString(inputString);
        assertEquals(classUnderTest.getInputString(), inputString);
    }
    
    @Test void appHasGetInputInteger() {
        App classUnderTest = new App();
        int inputInteger = 3;
        classUnderTest.setInputInteger(inputInteger);
        assertEquals(classUnderTest.getInputInteger(), inputInteger);
    }
}
