/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package welcome.to.java;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasHelloWorld() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getHelloWorld(), "Hello, World.");
    }

    @Test void appHasHelloJava() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.getHelloJava(), "Hello, Java.");
    }
}
