/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package welcome.to.java;

public class App {
    public String getHelloWorld() {
        return "Hello, World.";
    }
    public String getHelloJava() {
        return "Hello, Java.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getHelloWorld());
    }
}
