/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regex.exercise;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void checkIpPatternReturnsTrue() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.checkIpPattern("255.255.255.255"), true);
    }

    @Test void checkIpPatternReturnsFalse() {
        App classUnderTest = new App();
        assertEquals(classUnderTest.checkIpPattern("666.666.23.23"), false);
    }
}
