/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package regex.exercise;
import java.util.regex.Pattern;
import java.util.regex.Matcher;

public class App {
    MyRegex myRegex = new MyRegex();

    Pattern pattern = Pattern.compile(myRegex.getRegex());

    public boolean checkIpPattern(String ip) {
       Matcher matcher = pattern.matcher(ip);
       return matcher.find();
    } 

    public static void main(String[] args) {
        System.out.println(new App().checkIpPattern("0.0.0.0"));
    }
}
